#!/usr/bin/env lua
-- vim: syn=lua et tw
local util = require "util"
local inspect = require "inspect"
local simple_parser = require "simple_parser"
local manparser = require "manparser"

local str = nil
if not arg[1] then
  print(inspect(arg))
  io.stderr:write("no file specified!, Reading from stdin")
  str = io.read("a")
else
  str = util.getfilestring(arg[1])
end
--local str = io.read("a")
local cmd_table = manparser.make_table({"ls", "grep", "wc", "head", "tail", "date", "cut"})

local newtext = simple_parser(str, cmd_table)
io.stdout:write(newtext)

